#lang reader "reader.rkt"
HAI
    I HAS A X
    X R 2
    I HAS A Y ITZ WIN
    Y R MAEK X A NOOB
    2

    I HAS A TMP ITZ IT

    HOW IZ I STRINGIFY YR PARAM_A AN YR PARAM_B
       X R MAEK PARAM_A A YARN
       Y R MAEK PARAM_B A YARN
       GTFO
    IF U SAY SO

    HOW IZ I FIVEIFY
       FOUND YR 5
    IF U SAY SO

    I IZ STRINGIFY YR X AN YR Y MKAY
    I HAS A Z ITZ I IZ FIVEIFY MKAY

    I HAS A FUNKSHUN ITZ STRINGIFY

    I HAS A MATH ITZ SUM OF 1 AN PRODUKT OF MOD OF 4 AN 5 AN DIFF OF 6 AN 2 BTW equals 17


KTHXBYE
