#lang reader "reader.rkt"
HAI
    I HAS A X
    X R 2
    I HAS A Y ITZ WIN
    Y R MAEK X A NOOB

    HOW IZ I STRINGIFY YR PARAM_A AN YR PARAM_B
       X R MAEK PARAM_A A YARN
       Y R MAEK PARAM_B A YARN
       GTFO
    IF U SAY SO

    HOW IZ I FIVEIFY
       FOUND YR 5
    IF U SAY SO

    I IZ STRINGIFY YR X AN YR Y MKAY
    I HAS A Z ITZ I IZ FIVEIFY MKAY
KTHXBYE
