#lang lolcode
HAI 
  I HAS A ANIMAL ITZ "DOG"
  BOTH SAEM ANIMAL AN "CAT", O RLY?
    YA RLY, VISIBLE "J00 HAV A CAT"
    NO WAI, VISIBLE "J00 SUX"
  OIC

  BOTH SAEM ANIMAL AN "CAT", O RLY?
    YA RLY, VISIBLE "J00 HAV A CAT"
    MEBBE FAIL, VISIBLE "WONT PRINT"
    MEBBE WIN, VISIBLE "ELIF WORKS!"
    NO WAI, VISIBLE "J00 SUX"
  OIC

  ANIMAL R "CAT"

  BOTH SAEM ANIMAL AN "CAT", O RLY?
    YA RLY, VISIBLE "J00 HAV A CAT"
    NO WAI, VISIBLE "J00 SUX"
  OIC
KTHXBYE