#lang lolcode
HAI
    I IZ LAMDUH 5 LAMDONE MKAY
    VISIBLE IT
    I IZ LAMDUH YR X SUM OF 5 AN X LAMDONE YR 7 MKAY
    VISIBLE IT
    I IZ I IZ LAMDUH LAMDUH "nested" LAMDONE LAMDONE MKAY MKAY
    VISIBLE IT
KTHXBYE