#lang lolcode
HAI 
  VISIBLE SUM OF 1 AN 1
  VISIBLE PRODUKT OF 7 AN 3
  VISIBLE DIFF OF 10 AN 12
  VISIBLE QUOSHUNT OF 24 AN 6

  VISIBLE SUM OF 1 AN PRODUKT OF MOD OF 4 AN 5 AN DIFF OF 6 AN 2 BTW equals 17
  VISIBLE BIGGR OF SMALLR OF 1 AN 5 AN BIGGR OF 2 AN BIGGR OF 3 AN 4

KTHXBYE